# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
# 此目录下的程序，不是魔法，都是搞笑的
cc_binary(
    name = "magic1",
    srcs = ["magic1.cc"],
)

cc_binary(
    name = "magic4",
    srcs = ["magic4.c"],
)